config/routes.rb
Rails.application.routes.draw do

  resources :events do
    resources :tickets
  end
  root to: 'welcome#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destory', as: :logout

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_many :tickets

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :start_time_should_be_before_end_time

  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  private

  def start_time_should_be_before_end_time
    return unless start_time && end_time

    if start_time >= end_time
      errors.add(:start_time, 'は終了時刻よりも前に設定してください')
    end
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :comment, length: {maximum: 30}, allow_blank: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :created_events, class_name: 'Event', foreign_key: :owner_id
  has_many :tickets

  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    User.find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate, except: :show

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: '作成しました'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private

  def event_params
    params.required(:event).permit(
      :name, :place, :content, :start_time, :end_time
    )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destory
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate

  def new
    raise ActionController::RoutingError, 'ログイン状態で TicketsController#new にアクセス'
  end

  def create
    ticket = current_user.tickets.build do |t|
      t.event_id = params[:event_id]
      t.comment = params[:ticket][:comment]
    end
    if ticket.save
      flash[:notice] = 'イベントに参加表明しました'
      head 201
    else
      render json: {messages: ticket.errors.full_messages}, status: 422
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @events = Event.where('start_time > ?', Time.zone.now).order(:start_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<% now = Time.zone.now %>

<div class="page-header">
    <h1>イベント情報編集</h1>
</div>

<%= form_for(@event, class: 'form-horizontal', role: 'form') do |f| %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :start_time %>
    <div>
      <%= f.datetime_select :start_time, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_time %>
    <div>
      <%= f.datetime_select :end_time, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <div>
      <%= f.text_area :content, class: 'form-control', row: 10 %>
    </div>
  </div>
  <%= f.submit '更新', class: 'btn btn-default', data: { disable_with: '更新中・・・' } %>
<% end %>

app/views/events/new.html.erb
<% now = Time.zone.now %>

<div class="page-header">
    <h1>イベント作成</h1>
</div>

<%= form_for(@event, class: 'form-horizontal', role: 'form') do |f| %>
  <% if @event.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :start_time %>
    <div>
      <%= f.datetime_select :start_time, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_time %>
    <div>
      <%= f.datetime_select :end_time, start_year: now.year, end_year: now.year + 1 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <div>
      <%= f.text_area :content, class: 'form-control', row: 10 %>
    </div>
  </div>
  <%= f.submit '作成', class: 'btn btn-default', data: { disable_with: '作成中・・・' } %>
<% end %>

app/views/events/show.html.erb
<div class="page-header">
  <h1>
    <%= @event.name %>
  </h1>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        主催者
      </div>
      <div class="panel-body">
        <%= link_to("https://twitter.com/#{@event.owner.nickname}") do %>
          <%= image_tag @event.owner.image_url %>
          <%= "@#{@event.owner.nickname}" %>
        <% end %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        開催時間
      </div>
      <div class="panel-body">
        <%= @event.start_time.strftime('%Y/%m/%d %H:%M') %> - <%= @event.end_time.strftime('%Y/%m/%d %H:%M') %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        開催場所
      </div>
      <div class="panel-body">
        <%= @event.place %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        イベント内容
      </div>
      <div class="panel-body">
        <%= @event.content %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <% if @event.created_by?(current_user) %>
      <%= link_to 'イベントを編集する', edit_event_path(@event), class: 'btn btn-info btn-lg btn-block' %>
      <%= link_to 'イベントを削除する', event_path(@event), class: 'btn btn-danger btn-lg btn-block', method: :delete, data: {confirm: '本当に削除しますか？'} %>
    <% end %>
    <% if logged_in? %>
      <button class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#createTicket">
        参加する
      </button>
      <div class="modal fade" id="createTicket" tabindex="1" role="dialog" aria-labelledby="dialogHeader" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="dialogHeader">参加コメント</h4>
            </div>
            <%= form_for(@event.tickets.build, url: event_tickets_path(@event), remote: true) do |f| %>
              <div class="modal-body">
                <%= f.text_field :comment, class: 'form-control' %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
                <%= f.button '送信', class: 'btn btn-primary', data: {disable_with: '送信中・・・'} %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <%= link_to '参加する', new_event_ticket_path(@event), class: "btn btn-primary btn-lg btn-block" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSample</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'AwesomeEvents', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'イベントを作る', new_event_path %></li>
          <% if logged_in? %>
            <li><%= link_to 'ログアウト', logout_path %></li>
          <% else %>
            <li><%= link_to 'Twitterでログイン', '/auth/twitter' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </header>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1>イベント一覧</h1>
</div>
<div class="list-group">
  <% @events.each do |event| %>
    <%= link_to(event, class: 'list-group-item') do %>
    <h4 class="list-group-item-heading">
      <%= event.name %>
    </h4>
    <p class="list-group-item-text">
      <%= event.start_time.strftime('%Y/%m/%d %H:%M') %> - <%= event.end_time.strftime('%Y/%m/%d %H:%M') %>
    </p>
    <% end %>
  <% end %>
</div>